# HEPA Pipeline Demo

This pipeline is used to create visualizations for and summarize data from air quality sensors used in the Air Partners HEPA Pilot program.


```{r setup}
library(ggplot2)
library(tidyverse)
library(broom)
library(lubridate)
library(reticulate)
library(pracma)
library(cowplot)
library(reshape)
source("scripts/curve_fitting.R")
source("scripts/air_time_series.R")

# UNCOMMENT LINE BELOW FOR FIRST TIME RUNNING
# py_install("pandas")
source_python("read_pickle.py")

```


```{r}
# Download a file for analysis
df_sensor_sn <- read_pickle_file(
    "hepa-pckls/indoor-outdoor-pairs/48 Putnam Street #1/MOD-PM-00130.pckl"
)
# Filter out dataframe by timestamps
df_sensor_sn <- df_sensor_sn[!(is.na(df_sensor_sn$hepa_installed)), ]
# Replace all other nans with 0s
df_sensor_sn[is.na(df_sensor_sn)] <- 0
df_sensor_sn$hepa_installed <- as.logical(df_sensor_sn$hepa_installed)
```


```{r}
df_sensor_sn %>%
  ggplot(aes(timestamp, indoor_opc_bin0)) +
  geom_line(color = "blue") +
  geom_line(aes(y = outdoor_opc_bin0, color = "green"))
```

```{r}
# Convert all zeros in outdoor data to NA to prevent divide by zero errors
bin <- na.omit(str_match(names(df_sensor_sn), "^outdoor_([neph|opc].*)")[,1])
df_sensor_sn[, bin][df_sensor_sn[, bin] == 0] <- NA

# Add columns for sub 1nm particle count
df_sensor_sn["outdoor_particle_sum"] <-
  df_sensor_sn["outdoor_opc_bin0"] +
  df_sensor_sn["outdoor_opc_bin1"] +
  df_sensor_sn["outdoor_opc_bin2"]
df_sensor_sn["indoor_particle_sum"] <-
  df_sensor_sn["indoor_opc_bin0"] +
  df_sensor_sn["indoor_opc_bin1"] +
  df_sensor_sn["indoor_opc_bin2"]
```

```{r}
# Add Indoor / Outdoor ratio columns to the dataframe

# Create a list of datatypes
bin <- na.omit(str_match(names(df_sensor_sn), "^indoor_(.*)")[, 2])

# Create list of cols from og data
indoor <- df_sensor_sn[paste0("indoor_", bin)]
outdoor <- df_sensor_sn[paste0("outdoor_", bin)]

#create new col names
ratio_name <- paste0("ratio_", bin)

# Calculate new cols and add to dataframe
df_sensor_sn[ratio_name] <- indoor / outdoor
```


```{r}
# Find statistics for before and after

summary <-
  df_sensor_sn %>%
    group_by(hepa_installed) %>%
    summarize(across(starts_with("ratio"),
                    list(fifth = ~ quantile(.x, .05, na.rm = TRUE),
                          twentyfifth = ~ quantile(.x, .25, na.rm = TRUE),
                          seventyfifth = ~ quantile(.x, .75, na.rm = TRUE),
                          nintyfifth = ~ quantile(.x, .95, na.rm = TRUE),
                          mean = ~ mean(.x, na.rm = TRUE),
                          median = ~ median(.x, na.rm = TRUE)
                          )
                    )
              ) %>%
    pivot_longer(
      names_to = c(NA, "bin1", "bin2", ".value"),
      names_sep = "_",
      cols = -c(hepa_installed)
    )
```

```{r}
## Plotting the time series for PM1

# Get date of HEPA installation
installed_dates <-
  df_sensor_sn[!(df_sensor_sn$hepa_installed), ]
uninstalled_dates <-
  df_sensor_sn[df_sensor_sn$hepa_installed, ]

# Create time series
air_time_series(df_sensor_sn, "opc_pm1",
                logical_array = "hepa_installed",
                summary = summary,
                start_dates = installed_dates,
                end_dates = uninstalled_dates)
```

```{r}
## Plotting the time series for PM2.5

# Create time series plot
air_time_series(df_sensor_sn, "opc_pm25",
                logical_array = "hepa_installed",
                summary = summary,
                start_dates = installed_dates,
                end_dates = uninstalled_dates)
```

```{r}
## Plotting the time series for PM10

# Create time series plot
air_time_series(df_sensor_sn, "opc_pm10",
                logical_array = "hepa_installed",
                summary = summary,
                start_dates = installed_dates,
                end_dates = uninstalled_dates)
```


```{r}

# Create separate variable for this time series for ease of use
in_out <- df_sensor_sn$ratio_opc_pm25

# Plot the time series
plot(df_sensor_sn$timestamp, in_out,
  type = "l",
  main = "Indoor/Outdoor Ratio",
  xlab = "Time",
  ylab = "Ratio of indoor/outdoor concentrations",
  col = "navy")
  grid()
```

```{r}
# Get peaks of dataset
in_out[is.na(in_out)] <- 0
peaks <- findpeaks(in_out,
                   nups = 1,
                   ndowns = 1,
                   minpeakheight = 3,
                   minpeakdistance = 200,
                   threshold = 0)
print(peaks)

# Plot the peaks on top of current time series
plot(in_out,
  type = "l",
  main = "Indoor/Outdoor Ratio",
  xlab = "Time (indices)",
  ylab = "Ratio of indoor/outdoor concentrations",
  col = "navy")
  grid()
points(peaks[, 2], peaks[, 1], pch = 20, col = "maroon")
```

```{r}
# Get nearest valleys to those peaks
valleys <- get_first_valleys(in_out, peaks, 2)
print(valleys)

# Plot valleys on top of current time series
plot(in_out,
  type = "l",
  main = "Indoor/Outdoor Ratio",
  xlab = "Time (indices)",
  ylab = "Ratio of indoor/outdoor concentrations",
  col = "navy")
  grid()
points(peaks[, 2], peaks[, 1], pch = 20, col = "maroon")
points(valleys[, 2], valleys[, 1], pch = 20, col = "green")
```

```{r}
# Get the decay values between each peak and valley highlighted
decays <- curve_fitting(in_out, peaks, valleys)
decays
```

```{r}
# Get index of when HEPA was installed
hepa_install_idx <- match(TRUE, df_sensor_sn$hepa_installed)

# Create summary of decay values for before and after
decays["hepa_installed"] <- decays["peak_idx"] >= hepa_install_idx
decays["peak_width"] <- decays["valley_idx"] - decays["peak_idx"]

decay_sum <-
  decays %>%
    group_by(hepa_installed) %>%
    summarize(
      k_val_mean = mean(k_val, na.rm = TRUE),
      k_val_median = median(k_val, na.rm = TRUE),
      k_val_min = min(k_val, na.rm = TRUE),
      k_val_max = max(k_val, na.rm = TRUE),
      peak_hgt_mean = mean(peak_hgt, na.rm = TRUE),
      peak_wdh_mean = mean(peak_width, na.rm = TRUE)
    )
decay_sum
```

## Performing Pipeline on Multiple Datasets
```{r}
# Get list of all files
dirs <- list.dirs("hepa-pckls/indoor-outdoor-pairs", recursive = FALSE)
files <- list.files(dirs, full.names = TRUE)
```

## Heatmap

```{r}

# Vector that assigns each bin to a size (middle)
sizes <- c(
  "opc_bin0" = 0.405,
  "opc_bin1" = 0.56,
  "opc_bin2" = 0.83,
  "opc_bin3" = 1.15,
  "opc_bin4" = 1.5,
  "opc_bin5" = 2.0,
  "opc_bin6" = 2.65,
  "opc_bin7" = 3.5,
  "opc_bin8" = 4.6,
  "opc_bin9" = 5.85,
  "opc_bin10" = 7.25,
  "opc_bin11" = 9.0,
  "opc_bin12" = 11,
  "opc_bin13" = 13,
  "opc_bin14" = 15,
  "opc_bin15" = 17,
  "opc_bin16" = 19,
  "opc_bin17" = 21,
  "opc_bin18" = 23.5,
  "opc_bin19" = 26.5,
  "opc_bin20" = 29.5,
  "opc_bin21" = 32.5,
  "opc_bin22" = 35.5,
  "opc_bin23" = 38.5
)
# Vector that assigns each bin to a height
# In relation to the size of a bin, the minimum particle size in that bin
# should be {size - (height/2)} and the maximum {size + (height/2)}
heights <- c(
  "opc_bin0" = 0.11,
  "opc_bin1" = 0.20,
  "opc_bin2" = 0.34,
  "opc_bin3" = 0.30,
  "opc_bin4" = 0.40,
  "opc_bin5" = 0.60,
  "opc_bin6" = 0.70,
  "opc_bin7" = 1.0,
  "opc_bin8" = 1.2,
  "opc_bin9" = 1.3,
  "opc_bin10" = 1.5,
  "opc_bin11" = 2.0,
  "opc_bin12" = 2.0,
  "opc_bin13" = 2.0,
  "opc_bin14" = 2.0,
  "opc_bin15" = 2.0,
  "opc_bin16" = 2.0,
  "opc_bin17" = 2.0,
  "opc_bin18" = 3.0,
  "opc_bin19" = 3.0,
  "opc_bin20" = 3.0,
  "opc_bin21" = 3.0,
  "opc_bin22" = 3.0,
  "opc_bin23" = 3.0
)

```

```{r}
get_cols <- function(loc, bin_type) {
  cols <- na.omit(
    str_match(colnames(df_sensor_sn), paste0("^", loc, "_", bin_type, "_bin.*"))
  )[, 1]
  cols <- append(cols, "timestamp")
}

# Function that properly formats dataframe for the heatmap
df_bins <- function(df, loc) {
  df_out <- df[, get_cols(loc, "opc")]
  df_out[is.na(df_out)] <- 0
  df_out <-
    melt(df_out, id = c("timestamp"))
  df_out <-
    df_out %>%
      mutate(
        time = cut(timestamp, "hours"),
        sizes = sizes[gsub("^(ratio|indoor|outdoor)_", "", variable)],
        heights = heights[gsub("^(ratio|indoor|outdoor)_", "", variable)]
    )
}

df_ratio_bins <- df_bins(df_sensor_sn, "ratio")
df_indoor_bins <- df_bins(df_sensor_sn, "indoor")
df_outdoor_bins <- df_bins(df_sensor_sn, "outdoor")

```

```{r}
# Create heatmap for I/O ratio data
df_ratio_bins %>%
  ggplot(aes(time, sizes)) +
  geom_tile(aes(fill = value, height = heights)) +
  scale_x_discrete(
    breaks = df_ratio_bins$time[
      (wday(df_ratio_bins$timestamp) == 1) &
      (hour(df_ratio_bins$timestamp) == 0)
    ]
  ) +
  labs(
    title = "Heatmap of bin concentrations",
    y = "Particle diameter (um)",
    fill = "I/O Ratio"
  ) +
  ylim(c(0, 10)) +
  scale_fill_gradient(limits = c(0, 50), low = "blue", high = "orange") +
  theme(plot.margin = unit(c(1.2, 0.1, 1.2, 0.1), "cm"),
        axis.ticks.x = element_blank(),
        plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())
```

```{r}
# Create heatmap to examine PM concentrations indoors
df_indoor_bins %>%
  ggplot(aes(time, sizes)) +
  geom_tile(aes(fill = value, height = heights)) +
  scale_x_discrete(
    breaks = df_indoor_bins$time[
      (wday(df_indoor_bins$timestamp) == 1) &
      (hour(df_indoor_bins$timestamp) == 0)
    ]
  ) +
  labs(
    title = "Heatmap of bin concentrations",
    y = "Particle diameter (um)",
    fill = "Concentrations"
  ) +
  # ylim(c(0, 10)) +
  scale_y_log10() +
  scale_fill_gradient(limits = c(0, 50), low = "blue", high = "orange") +
  theme(plot.margin = unit(c(1.2, 0.1, 1.2, 0.1), "cm"),
        axis.ticks.x = element_blank(),
        plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())
```

```{r}
# Create heatmap to examine PM concentrations outside
df_outdoor_bins %>%
  ggplot(aes(time, sizes)) +
  geom_tile(aes(fill = value, height = heights)) +
  scale_x_discrete(
    breaks = df_outdoor_bins$time[
      (wday(df_outdoor_bins$timestamp) == 1) &
      (hour(df_outdoor_bins$timestamp) == 0)
    ]
  ) +
  labs(
    title = "Heatmap of bin concentrations",
    y = "Particle diameter (um)",
    fill = "Concentration"
  ) +
  ylim(c(0, 10)) +
  scale_fill_gradient(limits = c(0, 50), low = "blue", high = "orange") +
  theme(plot.margin = unit(c(1.2, 0.1, 1.2, 0.1), "cm"),
        axis.ticks.x = element_blank(),
        plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())
```
